/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfigsIdRouteImport } from './routes/_authenticated/configs.$id'
import { Route as AuthenticatedConfigsRouteImport } from './routes/_authenticated/configs.'
import { Route as ApiPublicConfigAppVersionRouteImport } from './routes/api/public/config.$app.$version'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfigsIdRoute = AuthenticatedConfigsIdRouteImport.update({
  id: '/configs/$id',
  path: '/configs/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfigsRoute = AuthenticatedConfigsRouteImport.update({
  id: '/configs/',
  path: '/configs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicConfigAppVersionRoute =
  ApiPublicConfigAppVersionRouteImport.update({
    id: '/api/public/config/$app/$version',
    path: '/api/public/config/$app/$version',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/configs/': typeof AuthenticatedConfigsRoute
  '/configs/$id': typeof AuthenticatedConfigsIdRoute
  '/api/public/config/$app/$version': typeof ApiPublicConfigAppVersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/configs': typeof AuthenticatedConfigsRoute
  '/configs/$id': typeof AuthenticatedConfigsIdRoute
  '/api/public/config/$app/$version': typeof ApiPublicConfigAppVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/configs/': typeof AuthenticatedConfigsRoute
  '/_authenticated/configs/$id': typeof AuthenticatedConfigsIdRoute
  '/api/public/config/$app/$version': typeof ApiPublicConfigAppVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/configs/'
    | '/configs/$id'
    | '/api/public/config/$app/$version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/configs'
    | '/configs/$id'
    | '/api/public/config/$app/$version'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/configs/'
    | '/_authenticated/configs/$id'
    | '/api/public/config/$app/$version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicConfigAppVersionRoute: typeof ApiPublicConfigAppVersionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configs/$id': {
      id: '/_authenticated/configs/$id'
      path: '/configs/$id'
      fullPath: '/configs/$id'
      preLoaderRoute: typeof AuthenticatedConfigsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configs/': {
      id: '/_authenticated/configs/'
      path: '/configs'
      fullPath: '/configs/'
      preLoaderRoute: typeof AuthenticatedConfigsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/config/$app/$version': {
      id: '/api/public/config/$app/$version'
      path: '/api/public/config/$app/$version'
      fullPath: '/api/public/config/$app/$version'
      preLoaderRoute: typeof ApiPublicConfigAppVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedConfigsRoute: typeof AuthenticatedConfigsRoute
  AuthenticatedConfigsIdRoute: typeof AuthenticatedConfigsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedConfigsRoute: AuthenticatedConfigsRoute,
  AuthenticatedConfigsIdRoute: AuthenticatedConfigsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicConfigAppVersionRoute: ApiPublicConfigAppVersionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
